"use client";
import { useMemo, useState } from "react";

const records = [
  { name:"Filesystem MCP", vendor:"Model Context Protocol", version:"2026.8.1", type:"Local", score:87, status:"Verified", tools:14, stars:"89.4k", risk:"Low" },
  { name:"GitHub MCP Server", vendor:"GitHub", version:"0.18.0", type:"Remote", score:74, status:"Review", tools:38, stars:"128.8k", risk:"Elevated" },
  { name:"Chrome DevTools MCP", vendor:"Google", version:"1.7.0", type:"Local", score:82, status:"Verified", tools:26, stars:"49k", risk:"Medium" },
  { name:"PostgreSQL MCP", vendor:"Model Context Protocol", version:"0.6.2", type:"Local", score:71, status:"Verified", tools:9, stars:"89.4k", risk:"Medium" },
  { name:"Sentry MCP", vendor:"Sentry", version:"0.12.1", type:"Hybrid", score:79, status:"Verified", tools:17, stars:"2.4k", risk:"Medium" },
  { name:"Slack MCP Server", vendor:"Model Context Protocol", version:"1.0.0", type:"Remote", score:68, status:"Review", tools:12, stars:"89.4k", risk:"Elevated" },
];
export default function Catalog(){ const [q,setQ]=useState(""); const shown=useMemo(()=>records.filter(r=>(r.name+r.vendor+r.type).toLowerCase().includes(q.toLowerCase())),[q]); return <main className="page-bg"><Header/><section className="catalog-hero shell"><div className="eyebrow"><span className="pulse"/> MCP INTELLIGENCE INDEX</div><h1>Find the MCP.<br/><span>Know the risk.</span></h1><p>Independently verified implementation, version, capability, and operational intelligence.</p><div className="search"><span>⌕</span><input aria-label="Search MCP intelligence" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search 71,584 MCP servers, packages, or vendors…"/><kbd>⌘ K</kbd></div><div className="catalog-stats"><span><strong>71,584</strong> tracked</span><span><strong>23,787</strong> local</span><span><strong>30,568</strong> remote</span><span><strong>12,469</strong> hybrid</span></div></section><section className="catalog shell"><div className="catalog-bar"><span>{shown.length} featured results</span><div><button>All</button><button>Verified</button><button>Local</button><button>Remote</button></div></div><div className="record-head"><span>IMPLEMENTATION</span><span>DEPLOYMENT</span><span>VERSION</span><span>TOOLS</span><span>RATING</span></div>{shown.map((r,i)=><a href={i===0?"/mcp/filesystem-mcp":"/mcp/filesystem-mcp"} className="record" key={r.name}><div><strong>{r.name}</strong><small>{r.vendor} · ★ {r.stars}</small></div><span className="type">{r.type}</span><code>{r.version}</code><span>{r.tools}</span><div className="record-score"><b>{r.score}</b><small>{r.status}</small></div></a>)}</section></main> }
function Header(){return <nav className="nav shell"><a className="brand" href="/"><span className="brand-mark">M</span>mcpSecurity<span className="dim">.cloud</span></a><div className="nav-links"><a href="/catalog">Intelligence</a><a href="/scanner">Scanner</a><a href="/methodology">Methodology</a></div><a className="button small" href="/scanner">Scan your MCPs ↗</a></nav>}
