import type { Metadata } from "next";
import { ContactButton } from "../contact-form";

export const metadata: Metadata = { title: "MCP Security Assessments", description: "Independent MCP security assessments with reproducible runtime evidence and prioritized remediation." };

export default function AssessmentsPage() {
  return <main className="page-bg">
    <nav className="nav shell"><a className="brand" href="/"><span className="brand-mark">M</span><span>mcpSecurity<span className="dim">.cloud</span></span></a><div className="nav-links"><a href="/enterprise">Enterprise</a><a href="/assessments">Assessments</a><a href="https://catalog.mcpsecurity.cloud/blog">Research</a><a href="https://catalog.mcpsecurity.cloud">Catalog</a></div><a className="button small" href="#contact">Request an assessment ↗</a></nav>
    <section className="service-hero shell"><div><div className="eyebrow"><span className="pulse"/> MCP SECURITY ASSESSMENTS</div><h1>Ship MCP products with evidence—not assumptions.</h1><p>We assess the MCP server you built, the servers your agents use, or the ecosystem exposure around your brand. You receive a technically defensible report engineering and security can act on.</p><div className="hero-actions"><a className="button" href="#contact">Scope an assessment →</a><a className="button ghost" href="#deliverables">See deliverables</a></div></div><aside className="assessment-summary"><div className="summary-top"><span>ASSESSMENT OUTPUT</span><b>Decision ready</b></div><div className="summary-score"><strong>4</strong><span>evidence layers</span></div><ul><li>Identity and supply chain</li><li>Runtime security behavior</li><li>MCP capabilities and permissions</li><li>Prioritized remediation</li></ul><p>Every confirmed finding includes the exact version, input, observed behavior, impact, and retest criteria.</p></aside></section>
    <section id="deliverables" className="deliverables shell"><div className="section-index">WHAT YOU RECEIVE</div><div className="deliverable-grid"><article><span>01</span><h2>Exposure map</h2><p>Verified servers, publishers, packages, exact versions, transports, and deployment paths.</p></article><article><span>02</span><h2>Runtime findings</h2><p>Reproducible evidence for exploitable behavior—not pattern matching or unsupported severity guesses.</p></article><article><span>03</span><h2>Capability review</h2><p>Tools, prompts, resources, permissions, trust boundaries, destructive actions, and sensitive data paths.</p></article><article><span>04</span><h2>Remediation plan</h2><p>Prioritized fixes, affected versions, compensating controls, owner-ready tickets, and a validation retest.</p></article></div></section>
    <section className="engagement shell"><div><div className="section-index">ENGAGEMENT OPTIONS</div><h2>One server, one portfolio, or the full fleet.</h2><p>Start narrowly when speed matters. Expand only when the evidence justifies it.</p></div><div className="engagement-list"><article><b>01</b><div><h3>Pre-release MCP assessment</h3><p>Focused exact-version testing, report, remediation workshop, and retest.</p></div></article><article><b>02</b><div><h3>Enterprise fleet assessment</h3><p>Identify what employees and agents use, verify it, and prioritize the highest-risk exposure.</p></div></article><article><b>03</b><div><h3>Brand ecosystem assessment</h3><p>Find official and unofficial MCPs using your name, APIs, credentials, and customer trust.</p></div></article></div></section>
    <section id="contact" className="contact-panel shell"><div><div className="section-index">REQUEST AN ASSESSMENT</div><h2>Tell us what you need to trust.</h2><p>Send the server, repository, package, fleet scope, or brand. We will reply with scope, timing, and a fixed engagement plan.</p></div><ContactButton source="Assessment page">Request an assessment →</ContactButton></section>
    <footer className="footer shell"><a className="brand" href="/"><span className="brand-mark">M</span>mcpSecurity.cloud</a><p>Independent MCP security intelligence and assessments.</p><div><a href="/enterprise">Enterprise</a><a href="https://catalog.mcpsecurity.cloud">Catalog</a></div></footer>
  </main>;
}
