import type { Metadata } from "next";

export const metadata: Metadata = { title: "Enterprise MCP Monitoring", description: "Continuous discovery, exact-version verification, and actionable MCP intelligence for enterprises." };

export default function EnterprisePage() {
  return <main className="page-bg"><nav className="nav shell"><a className="brand" href="/"><span className="brand-mark">M</span><span>mcpSecurity<span className="dim">.cloud</span></span></a><div className="nav-links"><a href="/enterprise">Enterprise</a><a href="/assessments">Assessments</a><a href="https://catalog.mcpsecurity.cloud/blog">Research</a><a href="https://catalog.mcpsecurity.cloud">Catalog</a></div><a className="button small" href="mailto:security@mcpsecurity.cloud?subject=Enterprise%20MCP%20monitoring">Talk to us ↗</a></nav>
  <section className="service-hero shell"><div><div className="eyebrow"><span className="pulse"/> CONTINUOUS MCP SECURITY</div><h1>Every MCP. Every version. Continuously verified.</h1><p>See which MCP implementations matter to your organization, what they can do, whether exact versions are vulnerable, and what changed since the last decision.</p><div className="hero-actions"><a className="button" href="mailto:security@mcpsecurity.cloud?subject=Enterprise%20MCP%20monitoring">Request an enterprise briefing →</a><a className="button ghost" href="/assessments">Start with an assessment</a></div></div><aside className="assessment-summary"><div className="summary-top"><span>ORGANIZATION RISK SIGNAL</span><b>Continuously monitored</b></div><div className="summary-score"><strong>24/7</strong><span>change detection</span></div><ul><li>Organization-specific inventory</li><li>Exact-version vulnerability evidence</li><li>Capability and publisher changes</li><li>Actionable owner-ready alerts</li></ul></aside></section>
  <section className="contact-panel shell"><div><div className="section-index">ENTERPRISE MONITORING</div><h2>Turn ecosystem noise into an owned security program.</h2><p>Start with a scoped assessment. Continue with monitoring when you know which exposure is worth watching.</p></div><a className="button" href="mailto:security@mcpsecurity.cloud?subject=Enterprise%20MCP%20monitoring">Book a briefing →</a></section>
  <footer className="footer shell"><a className="brand" href="/"><span className="brand-mark">M</span>mcpSecurity.cloud</a><p>Independent MCP security intelligence and assessments.</p><div><a href="/assessments">Assessments</a><a href="https://catalog.mcpsecurity.cloud">Catalog</a></div></footer></main>;
}
